### ISSUE TITLE
[ADD/BUG] Change of connected Vault on change in extension

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vulticonnect#29]
When changing/selecting a different Vault in VultiConnect, please also trigger a change on the connected dApp/interface. 

Otherwise user could be connected with vault A, changes in Vulticonnect to vault B in VultiConnect, wants to swap/send with vault A on the dApp but actually sends with vault B because that one is selected in  VultiConnect.

**Comment by Ehsan-saradar** [comment]
Fixed in #59
