### ISSUE TITLE
[ADD] Estimate Gas action

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vulticonnect#38]
To be able to do swaps over ChainFlip, we need to have the action `estimateGas()` to calculate the gas before starting the tx otherwise it is not possible to do swaps over chainflip.

![image](https://github.com/user-attachments/assets/5e4136a1-4e67-43af-a8ef-7d275d962247)

**Comment by Ehsan-saradar** [comment]
Fixed in #59
