### ISSUE TITLE
[BUG] Open Desktop App not working with windows

### ISSUE THREAD

**Issue by realpaaao** [vultisig/vulticonnect#39]
When pressing `open desktop app` button and having windows installed it does not open.

**Comment by melsonius** [comment]
I recently encountered this as well.  It seems that the issue is that the installer didn't create a protocol handler in the Windows registry to handle the vultisig:// URIs.

**Comment by Ehsan-saradar** [comment]
@realpaaao It's not vulticonnect issue. its an issue in vultisig windows app and we should resolve it there
